name: Test case request
description: Write test cases
title: "test: "
labels: ["test", "todo"]
body:
  - type: textarea
    id: description
    attributes:
      label: Test case description
      description: A small description of the test case.
      value: "Describe..."
    validations:
      required: true
